export enum DeliveryStatus {
  PAYMENT_VALIDATION = 'PAYMENT_VALIDATION',
  IN_PREPARATION = 'IN_PREPARATION',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  FINISHED = 'FINISHED',
}

export const DeliveryStatusOrder = [
  'PAYMENT_VALIDATION',
  'IN_PREPARATION',
  'OUT_FOR_DELIVERY',
  'FINISHED',
];
