export enum DeliveryStatus {
  PAYMENT_VALIDATION = 'PAYMENT_VALIDATION',
  TO_PRINT = 'TO_PRINT',
  IN_PREPARATION = 'IN_PREPARATION',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
}

export const DeliveryStatusOrder = [
  'PAYMENT_VALIDATION',
  'TO_PRINT',
  'IN_PREPARATION',
  'OUT_FOR_DELIVERY',
  'FINISHED',
  'CANCELED',
];
