export const ProductsCategory = {
  PIZZA_TRADICIONAL: 'PIZZA_TRADICIONAL',
  PIZZA_PREMIUM: 'PIZZA_PREMIUM',
  PIZZA_ESPECIAL: 'PIZZA_ESPECIAL',
  PIZZA_DOCE: 'PIZZA_DOCE',
  BEBIDAS: 'BEBIDAS',
  HAMBURGUER: 'HAMBURGUER',
  PETISCO: 'PETISCO',
};
